### PR TITLE
[12.0][3697][ADD] product_security

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3697](https://www.quartile.co/web#id=3697&cids=3&model=project.task&view_type=form)

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
pre-commit fixed the website key for other modules.

**Comment by AungKoKoLin1997** [comment]
@rinaldifirdaus  Please help me to add background in readme fragment.

**Comment by AungKoKoLin1997** [comment]
Seem like we need to rebase after this PR got merged https://github.com/qrtl/asx-custom/pull/100.

**Comment by yostashiro** [comment]
> Seem like we need to rebase after this PR got merged #100.

@AungKoKoLin1997 I guess you need to update that PR to apply the latest content from the template.

Please also check with Aldi on the module name.  I think it's a bit confusing that we have a module with the same name with different content for another customer.

**Comment by AungKoKoLin1997** [comment]
Closing this task and will create new one. There is conflict when rebase.

**Pull request closed without merging**
